language: java
sudo: false

jdk:
  - oraclejdk8

install: true
script: ./travis.sh

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "jn7b+2dNJpC7QPUneOwvNHzVwAnNDP2Cx17ZHpzNoR294PQ/IoUE86pLzkQmzRGLygoDLvJZ9ftvSEv5nbeb72pVzabZnFcU8w1u9XICzL6J3bR+SYQKJtlEeI8vO6/OPVzOFaG4e2qPW5iZW783hXh3rFi1KNyq8OQnq2SwKTs="
